[package]
name = "pytja_core"
version = "0.1.0"
edition = "2021"

[dependencies]
# Fehlerbehandlung
tokio = { version = "1.0", features = ["full"] }

# ENTERPRISE DATABASE DRIVER (SQLx)
# Unterstützt SQLite (embedded) und Postgres (Server) gleichzeitig!
sqlx = { version = "0.7", features = [
    "runtime-tokio",
    "tls-native-tls",
    "sqlite",
    "postgres",
    "macros",
    "chrono",
    "uuid"
] }

# Serialisierung
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
async-trait = "0.1"
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4"] }
anyhow = "1.0"

config = "0.13"
dotenv = "0.15"

[dev-dependencies]
uuid = { version = "1.0", features = ["v4"] }
tokio = { version = "1.0", features = ["full", "macros"] } # Damit wir #[tokio::test] nutzen können
