syntax = "proto3";
package pytja;

// Der Service definiert, was der Server kann
service PytjaService {
    rpc Ping (PingRequest) returns (PingResponse);
    rpc ListDirectory (ListRequest) returns (ListResponse);
    rpc CreateNode (CreateNodeRequest) returns (ActionResponse);
}

// --- Messages (Datenpakete) ---

message PingRequest {
    string message = 1;
}

message PingResponse {
    string message = 1;
    string server_version = 2;
    bool is_ready = 3;
}

message ListRequest {
    string path = 1;
    string auth_token = 2;
}

message FileInfo {
    string name = 1;
    bool is_folder = 2;
    uint64 size = 3;
    string owner = 4;
    uint32 permissions = 5;
    double created_at = 6;
}
message ListResponse {
    repeated FileInfo files = 1;
}

message CreateNodeRequest {
    string path = 1;
    bool is_folder = 2;
    bytes content = 3;
    string lock_password = 4;
    string owner = 5;
}

message ActionResponse {
    bool success = 1;
    string message = 2;
}