[package]
name = "pytja_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tonic = "0.10"
prost = "0.12"
colored = "2.0"

# Unsere eigenen Module
pytja_proto = { path = "../pytja_proto" }
pytja_core = { path = "../pytja_core" } # Wir brauchen Zugriff auf die DB Logik