[package]
name = "pytja_server"
version = "0.1.0"
edition = "2021"
default-run = "pytja_server"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tonic = "0.10"
prost = "0.12"
colored = "2.0"

# Unsere eigenen Module
pytja_proto = { path = "../pytja_proto" }
pytja_core = { path = "../pytja_core" } # Wir brauchen Zugriff auf die DB Logik
chrono = "0.4.43"
uuid = { version = "1.20.0", features = ["v4"] }
futures-util = "0.3.31"
tokio-stream = "0.1.18"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
serde_json = "1.0.149"
tracing = "0.1.44"
